### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by pbrubaker** [Angelo1211/SoftwareRenderer#1]
Hey Angel,

I saw your post on twitter and checked the project.  I've been looking for candidates that I can use as experiments for ISPC, the Intel SPMD Program Compiler.  I'd love to use this project, you've done a very good job with organization so I think it's a good fit.  However I can't experiment with your code as it's unlicensed.

If you were to choose MIT or Apache 2.0 I'd love to experiment with ISPC implementations for certain functions.  

Namely:
void SoftwareRenderer::drawTriangularMesh(Model * currentModel)
void Rasterizer::drawTriangles(Vector3f *vertices, IShader &shader, Buffer<Uint32> *pixelBuffer, Buffer<float> *zBuffer)

Cheers,

Pete

**Comment by Angelo1211** [comment]
Hey Pete,

Thanks for your interest in my project! I apologize for the inconvenience, I just went ahead and added a MIT license to the project.

 Hope that helps your experimentation and let me know how it goes!

Thanks,

Angel
