### ISSUE TITLE
Improve build and usage instructions

### ISSUE THREAD

**Issue by dov** [Angelo1211/SoftwareRenderer#2]
It is not clear how to build and use the software. I initially did `cmake .; make; ./softwareRenderer`. Only after I did `mkdir build; cd build; cmake ..; make; ./softwareRenderer` could I test the program.

**Comment by reppolice** [comment]
Your second try is the default for cmake users, sure he could mention it but it is kinda non issue.

**Comment by dov** [comment]
I guess I'm not using cmake enough. In comparison a typical automake programs contain an INSTALL file that outlines the steps of doing `./configure; make`. But I agree it is quite a trivial issue.

**Comment by reppolice** [comment]
I was also a victim of this when I first came across CMake. Luckily it was solvable after looking into a couple of other projects. Much more luck is needed if any of the 10 thousand cmake options bombs out though :) And other build systems don't even have this default and you have to fish into their configuration files.

**Comment by Angelo1211** [comment]
I agree that cmake is not the best building tool out there, I personally don't use it anymore.
