### ISSUE TITLE
A more "standard" build

### ISSUE THREAD

**Issue by reppolice** [Angelo1211/SoftwareRenderer#4]
I saw you produced a binary for Windows with some variation of the Mingw theme, but I was curious how the Visual Studio toolchain would fair. It looks like there are bits of syntax and constants that are not part of the C++ spec, so I inserted into geometry.h

`#ifndef M_PI
    #define M_PI 3.14159265358979323846
#endif
# define M_1_PIf32	 (0.318309886183790671537767526745028724) /* 1/pi */`

That went OK for a while but I borked hard with:

`
C:\Repos\SoftwareRenderer\include\shader.h(286): warning C4305: 'initializing': truncation from 'double' to 'float'
C:\Repos\SoftwareRenderer\include\shader.h(304): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
C:\Repos\SoftwareRenderer\include\shader.h(314): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
C:\Repos\SoftwareRenderer\include\shader.h(381): error C2131: expression did not evaluate to a constant
C:\Repos\SoftwareRenderer\include\shader.h(378): note: failure was caused by a read of a variable outside its lifetime
C:\Repos\SoftwareRenderer\include\shader.h(378): note: see usage of 'this'
C:\Repos\SoftwareRenderer\include\shader.h(382): error C2131: expression did not evaluate to a constant
C:\Repos\SoftwareRenderer\include\shader.h(378): note: failure was caused by a read of a variable outside its lifetime
C:\Repos\SoftwareRenderer\include\shader.h(378): note: see usage of 'this'
C:\Repos\SoftwareRenderer\include\shader.h(383): error C2131: expression did not evaluate to a constant
C:\Repos\SoftwareRenderer\include\shader.h(378): note: failure was caused by a read of a variable outside its lifetime
C:\Repos\SoftwareRenderer\include\shader.h(378): note: see usage of 'this'
C:\Repos\SoftwareRenderer\include\shader.h(386): error C2131: expression did not evaluate to a constant
C:\Repos\SoftwareRenderer\include\shader.h(378): note: failure was caused by a read of a variable outside its lifetime
C:\Repos\SoftwareRenderer\include\shader.h(378): note: see usage of 'this'
C:\Repos\SoftwareRenderer\include\shader.h(387): error C2131: expression did not evaluate to a constant
C:\Repos\SoftwareRenderer\include\shader.h(378): note: failure was caused by a read of a variable outside its lifetime
C:\Repos\SoftwareRenderer\include\shader.h(378): note: see usage of 'this'
C:\Repos\SoftwareRenderer\include\shader.h(388): error C2131: expression did not evaluate to a constant
C:\Repos\SoftwareRenderer\include\shader.h(378): note: failure was caused by a read of a variable outside its lifetime
C:\Repos\SoftwareRenderer\include\shader.h(378): note: see usage of 'this'
C:\Repos\SoftwareRenderer\include\shader.h(389): error C2131: expression did not evaluate to a constant
C:\Repos\SoftwareRenderer\include\shader.h(378): note: failure was caused by a read of a variable outside its lifetime
C:\Repos\SoftwareRenderer\include\shader.h(378): note: see usage of 'this'
C:\Repos\SoftwareRenderer\include\shader.h(390): error C2131: expression did not evaluate to a constant
C:\Repos\SoftwareRenderer\include\shader.h(378): note: failure was caused by a read of a variable outside its lifetime
C:\Repos\SoftwareRenderer\include\shader.h(378): note: see usage of 'this'
C:\Repos\SoftwareRenderer\include\shader.h(391): error C2131: expression did not evaluate to a constant
C:\Repos\SoftwareRenderer\include\shader.h(378): note: failure was caused by a read of a variable outside its lifetime
C:\Repos\SoftwareRenderer\include\shader.h(378): note: see usage of 'this'
C:\Repos\SoftwareRenderer\include\shader.h(392): error C2131: expression did not evaluate to a constant
C:\Repos\SoftwareRenderer\include\shader.h(378): note: failure was caused by a read of a variable outside its lifetime
C:\Repos\SoftwareRenderer\include\shader.h(378): note: see usage of 'this'
C:\Repos\SoftwareRenderer\include\shader.h(393): error C2131: expression did not evaluate to a constant
C:\Repos\SoftwareRenderer\include\shader.h(378): note: failure was caused by a read of a variable outside its lifetime
C:\Repos\SoftwareRenderer\include\shader.h(378): note: see usage of 'this'
C:\Repos\SoftwareRenderer\include\shader.h(399): error C3863: array type 'Vector3f [maxLights]' is not assignable
C:\Repos\SoftwareRenderer\include\shader.h(405): error C3001: 'simd': expected an OpenMP directive name
C:\Repos\SoftwareRenderer\include\shader.h(407): error C3863: array type 'Vector3f [maxLights]' is not assignable
C:\Repos\SoftwareRenderer\include\shader.h(409): error C3863: array type 'float [maxLights]' is not assignable
C:\Repos\SoftwareRenderer\include\shader.h(414): error C3863: array type 'float [maxLights]' is not assignable
C:\Repos\SoftwareRenderer\include\shader.h(415): error C3863: array type 'float [maxLights]' is not assignable
C:\Repos\SoftwareRenderer\include\shader.h(417): error C3863: array type 'Vector3f [maxLights]' is not assignable
C:\Repos\SoftwareRenderer\include\shader.h(418): error C3863: array type 'float [maxLights]' is not assignable
C:\Repos\SoftwareRenderer\include\shader.h(419): error C3863: array type 'Vector3f [maxLights]' is not assignable
C:\Repos\SoftwareRenderer\include\shader.h(422): error C3863: array type 'Vector3f [maxLights]' is not assignable
C:\Repos\SoftwareRenderer\include\shader.h(425): warning C4305: 'argument': truncation from 'double' to 'const T'

`

Unfortunately I don't know at all what happens around line 378 but here it is

` const int maxLights = numLights;

        //Fresnel, normal distribution function and geometry occlusion 
        Vector3f F[maxLights];`

**Comment by Angelo1211** [comment]
Hey! I apologize for the delayed response. There's a windows branch for the project that fixes all of these issues. Let me know if that works better for you. Cheers!
